const fs = require('fs');
const path = require('path');

// Define the number of files you want to generate
const numberOfFiles = 2000;

// Base directory path where the files will be created
const baseDir = '/Users/Shared/Laptop/Github/webforj-hello-world/src/main/java/samples/views/';

// Template content for the Java file
const javaTemplate = (className) => `
package samples.views.autogenerated;

import com.webforj.component.Composite;
import com.webforj.component.html.elements.H1;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.router.annotation.FrameTitle;
import com.webforj.router.annotation.Route;

import samples.views.MainLayout;

@Route(outlet = MainLayout.class)
@FrameTitle("${className}")
public class ${className} extends Composite<FlexLayout> {

  public ${className}() {
    getBoundComponent().add(new H1("${className}"));
  }
}
`;

// Function to create a folder if it doesn't exist
function createFolder(folderPath) {
  if (!fs.existsSync(folderPath)) {
    fs.mkdirSync(folderPath, { recursive: true });
    console.log(`Created folder: ${folderPath}`);
  } else {
    console.log(`Folder already exists: ${folderPath}`);
  }
}

// Function to create Java files
function createJavaFiles(numFiles) {
  const folderName = 'autogenerated';
  const folderPath = path.join(baseDir, folderName);
  createFolder(folderPath); // Create 'autogenerated' folder only once

  for (let i = 1; i <= numFiles; i++) {
    const className = `View${i}View`;
    const filePath = path.join(folderPath, `${className}.java`);
    const fileContent = javaTemplate(className);

    fs.writeFileSync(filePath, fileContent, 'utf8');
    console.log(`Created Java file: ${filePath}`);
  }
}

// Create the desired number of files
createJavaFiles(numberOfFiles);
