
package samples.views.autogenerated;

import com.webforj.component.Composite;
import com.webforj.component.html.elements.H1;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.concern.HasVisibility;
import com.webforj.router.annotation.FrameTitle;
import com.webforj.router.annotation.Route;

import samples.views.MainLayout;

@Route(outlet = MainLayout.class)
@FrameTitle("View2000View")
public class View2000View extends Composite<FlexLayout> implements HasVisibility<View2000View> {

  public View2000View() {
    getBoundComponent().add(new H1("View2000View"));
  }
}
