
package samples.views.autogenerated;

import com.webforj.component.Composite;
import com.webforj.component.html.elements.H1;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.concern.HasVisibility;
import com.webforj.router.annotation.FrameTitle;
import com.webforj.router.annotation.Route;

import samples.views.MainLayout;

@Route(outlet = MainLayout.class)
@FrameTitle("View1730View")
public class View1730View extends Composite<FlexLayout> implements HasVisibility<View1730View> {

  public View1730View() {
    getBoundComponent().add(new H1("View1730View"));
  }
}
